metrics: fix the issue of special characters being escaped in passwords
coroot/coroot-cluster-agent pull request #3
Opened 2024-08-08 05:23 UTC by wenhuwang

Fixed: #2 

Here are the reasons
```
	userPass1 := url.UserPassword("root", "123%abc")
	fmt.Printf("userPass1: %s\n", userPass1)

	userPass2 := fmt.Sprintf("%s:%s", "root", "123%abc")
	fmt.Printf("userPass2: %s\n", userPass2)

	// userPass1: root:123%25abc
	// userPass2: root:123%abc
```

2024-08-13 11:00 UTC, apetruhin commented
@wenhuwang,

It turns out that user and password should be escaped for Postgres, but should not be escaped for Mysql.

```go
package main

import (
	"fmt"
	"net/url"

	"github.com/go-sql-driver/mysql"
	"github.com/lib/pq"
)

func main() {
	address := "127.0.0.1"
	user := "user"
	password := "pwd%pwd"

	dsn := fmt.Sprintf("postgresql://%s@%s/postgres", fmt.Sprintf("%s:%s", user, password), address)
	kvs, err := pq.ParseURL(dsn)
	fmt.Println(err) // parse "postgresql://user:pwd%pwd@127.0.0.1/postgres": invalid URL escape "%pw"

	dsn = fmt.Sprintf("postgresql://%s@%s/postgres", url.UserPassword(user, password).String(), address)
	kvs, err = pq.ParseURL(dsn)
	fmt.Println(err) // <nil>
	fmt.Println(kvs) // dbname='postgres' host='127.0.0.1' password='pwd%pwd' user='user'

	dsn = fmt.Sprintf("%s@tcp(%s)/mysql", fmt.Sprintf("%s:%s", user, password), address)
	cfg, err := mysql.ParseDSN(dsn)
	fmt.Println(err)        // <nil>
	fmt.Println(cfg.Passwd) // pwd%pwd

	dsn = fmt.Sprintf("%s@tcp(%s)/mysql", url.UserPassword(user, password).String(), address)
	cfg, err = mysql.ParseDSN(dsn)
	fmt.Println(err)        // <nil>
	fmt.Println(cfg.Passwd) // pwd%25pwd
}
```

2024-08-15 07:13 UTC, apetruhin requested changes
Please revert changes for Postgres.

2024-08-19 01:29 UTC, wenhuwang commented
OK, I'll handle it asap.

2024-08-19 14:51 UTC, apetruhin approved these changes

2024-08-19 14:51 UTC, merged